Order model tests
Smoke-ck/Orders_v2 pull request #2
Opened 2022-01-25 15:44 UTC by Smoke-ck

2022-01-25 15:46 UTC, Smoke-ck commented
Blocked by #1

2022-01-31 16:18 UTC, Surzhko requested changes
Some small comments

2022-01-31 16:18 UTC, Surzhko commented on .ruby-gemset
> +rails7
Shouldn't be in the repo

2022-01-31 16:18 UTC, Surzhko commented on app/models/order.rb
> +  validates :check_out, presence: { message: "must be in the format XX:XX" }
```suggestion
  validates :check_out, presence: { message: "required and must be in the format XX:XX" }
```
It could be not obvious that it's required

2022-01-31 16:18 UTC, Surzhko commented on app/views/devise/shared/_navbar.html.erb
> +</nav>
:+1:

2022-01-31 16:18 UTC, Surzhko commented on spec/support/config/capybara.rb
> +end
No new line

2022-02-01 13:00 UTC, Surzhko approved these changes

2022-02-01 13:00 UTC, merged